todoproject/todoapp/urls.py
from.import views
from django.urls import path
app_name='todoapp'
urlpatterns = [
    path('',views.add,name='add'),
    path('delete/<int:id>/',views.delete,name='delete'),
    path('edit/<int:id>/',views.edit,name='edit'),
    path('cbvhome/',views.Tasklistview.as_view(),name='cbvhome'),
    path('cbvdetail/<int:pk>/', views.Taskdetailview.as_view(), name='cbvdetail'),
    path('cbvdetail/<int:pk>/', views.Taskupdateview.as_view(), name='cbvupdate'),
    path('cbvdelete/<int:pk>/', views.Taskdeleteview.as_view(), name='cbvdelete'),

]

todoproject/todoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from todoproject import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("todoapp.urls"))

]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

todoproject/todoapp/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    objects = None
    name=models.CharField(max_length=250)
    priority=models.IntegerField()
    date=models.DateField()
    def __str__(self):
        return self.name

todoproject/todoapp/forms.py
from .models import Task
from django import forms

class TodoForm(forms.ModelForm):
    class Meta:
        model=Task
        fields=['name','priority','date']

todoproject/todoapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from . models import Task
from . forms import TodoForm
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView,DeleteView

class Tasklistview(ListView):
    model=Task
    template_name = 'home.html'
    context_object_name = 'task1'

class Taskdetailview(DetailView):
    model=Task
    template_name = 'details.html'
    context_object_name = 'task'

class Taskupdateview(UpdateView):
    model=Task
    template_name = 'update.html'
    context_object_name = 'task'
    fields = ('name','priority','date')

def get_success_url(self):
    return reverse_lazy('cbvdetail',kwarg={'pk':self.object.id})

class Taskdeleteview(DetailView):
    model = Task
    template_name = 'delete.html'
    Success_url=reverse_lazy('cbvhome')

# Create your views here.
def add(request):
    task1 = Task.objects.all()
    if request.method=='POST':
        name=request.POST.get('task','')
        priority=request.POST.get('priority','')
        date = request.POST.get('date', '')
        task=Task(name=name,priority=priority,date=date)
        task.save()
    return render(request,'home.html',{'task1':task1})

def delete(request,id):
    task=Task.objects.get(id=id)
    if request.method=='POST':
        task.delete()
        return redirect('/')
    return render(request,'delete.html')

def edit(request,id):
    task=Task.objects.get(id=id)
    f=TodoForm(request.POST or None,instance=task)
    if f.is_valid():
        f.save()
        return redirect('/')
    return render(request,'edit.html',{'f':f,'task':task})

todoproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>base</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

todoproject/templates/delete.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <p> Are you sure this task is done?</p>
    <input type="submit">
</form>
{% endblock %}

todoproject/templates/details.html
{% extends 'base.html' %}
{% block content %}
 <div class="shadow card">
        <div class="card-body">
            <h5 class="card-title">{{task.name}}<br></h5>
            <p><b>{{task.priority}}</b></p><br>
             <p><b>{{task.date}}</b></p>
            <a href="{% url 'todoapp:delete' task.id %}" class="btn btn-danger">Done</a>
               <a href="{% url 'todoapp:edit' task.id %}" class="btn btn-success">UPDATE</a>
        </div>
    </div>
{% endblock %}

todoproject/templates/edit.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {{f.as_p}}
    <button type="submit">Confirm</button>
</form>
{% endblock %}

todoproject/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
          <div class ="banner">
        <div class="banner-text">
            <h1>TODO</h1>
          </div>
       </div>
      </div>
   </div>
</div>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
    <div class="container">
        <div class="row">
         <div class="col-md-6">
             <form method="POST" class="p-3 shadow">
            {% csrf_token %}
  <div class="form-group">
    <input type="text" class="form-control" name="task" placeholder="Task name">
  </div>
        <div class="form-group">
    <input type="text" class="form-control" name="priority" placeholder="priority">
            </div>
                 <div class="form-group">
    <input type="date" class="form-control" name="date" placeholder="enter date">
            </div>
    <input type="submit" class="btn btn-success">
            </form>

</div>
            <div class="col-md-6">
    <h4>Task to be completed</h4>
    {% for i in task1 %}
    <div class="shadow card">
        <div class="card-body">
            <h5 class="card-title">{{i.name}}<br></h5>
            <p><b>{{i.priority}}</b></p><br>
             <p><b>{{i.date}}</b></p>
            <a href="{% url 'todoapp:delete' i.id %}" class="btn btn-danger">Done</a>
               <a href="{% url 'todoapp:edit' i.id %}" class="btn btn-success">UPDATE</a>
        </div>
    </div>
                <br>
{% endfor %}
</div>

    </div>
</div>
</body>
</html>
{% endblock  %}

todoproject/templates/update.html
{% extends 'base.html' %}
{% block content %}

<div class="card">
    <div class="card-header">
        <div class="card-title">
            Task Updated
        </div>
        <div class="card-body">
            <form method="POST">
                {% csrf-token %}
                <button type="submit">Update</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}